apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kjkt5kw1e-go
  janus-idp.io/tekton: kjkt5kw1e-go
  backstage.io/kubernetes-id: kjkt5kw1e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kjkt5kw1e-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
