apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kjkt5kw1e-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kjkt5kw1e-go 
  name: kjkt5kw1e-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kjkt5kw1e-go 
